# Generated by Django 4.2.3 on 2023-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shgapp', '0002_delete_branchdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchcode', models.BigIntegerField()),
                ('branchname', models.CharField(max_length=255)),
                ('br_manager', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
    ]
