# Generated by Django 4.2.3 on 2023-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_code', models.BigIntegerField()),
                ('society_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
    ]
