# Generated by Django 4.2.3 on 2023-07-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgapp', '0004_societydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='shgdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('ac_open_through', models.CharField(max_length=255)),
                ('sycode', models.BigIntegerField()),
                ('society_name', models.CharField(max_length=255)),
                ('branchname', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('group_no', models.BigIntegerField()),
                ('group_name', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('group_type', models.CharField(max_length=255)),
                ('No_of_members', models.BigIntegerField()),
                ('of_which_sc', models.BigIntegerField()),
                ('of_which_st', models.BigIntegerField()),
                ('total_savings', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
            ],
        ),
    ]
